#!/bin/bash

gRNATable=$1
outDir=$2
overhang=$3

library_name=${gRNATable##*/}
/usr/local/python3/bin/python3 /usr/local/bin/build_ref_genome.py -i $gRNATable -o $outDir/$library_name

fa_size=$(seqkit stats $outDir/$library_name.fa | tail -n1 | sed 's/ \+/\t/g' | cut -f5 | sed 's/,//g')
fa_count=$(seqkit stats $outDir/$library_name.fa | tail -n1 | sed 's/ \+/\t/g' | cut -f7 | sed 's/,//g')

sa_index_bases=$(echo "l($fa_size)/l(2)/2" | bc -l)
sa_index_bases=$((${sa_index_bases%%.*}-1))
bin_bits=$(echo "l($fa_count)/l(2)" | bc -l)
bin_bits=${bin_bits%%.*}

mapping --runMode genomeGenerate --genomeDir $outDir \
     --genomeFastaFiles $outDir/$library_name.fa \
     --sjdbGTFfile $outDir/$library_name.gtf \
     --sjdbOverhang $overhang --genomeSAindexNbases $sa_index_bases --genomeChrBinNbits $bin_bits